version: "3"
services:
  influx:
    image: tutum/influxdb:0.8.8
    ports:
      - "8086:8086"
      - "8083:8083"
      - "4444:4444/udp"
    environment:
      - PRE_CREATE_DB=metrics
      - UDP_DB=metrics
  elasticsearch:
    image: elasticsearch:5
    ports:
      - "9200:9200"
  zookeeper:
      image: confluentinc/cp-zookeeper:5.0.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper

  influx_wait:
    image: kpndigital/tox
    links:
      - influx
    command: sh -c "while ! nc -w1 -z influx 8086; do sleep 1; done"

  elasticsearch_wait:
    image: kpndigital/tox
    links:
      - elasticsearch
    command: sh -c "while ! nc -w1 -z elasticsearch 9200; do sleep 1; done"

  kafka_wait:
    image: confluentinc/cp-kafka
    links:
      - kafka
    command: sh -c "while ! cub kafka-ready -b kafka:9092 1 1; do sleep 1; done"

  app:
    build: .
    volumes:
      - .:/app
    command: tox
    links:
      - influx_wait
      - influx
      - elasticsearch_wait
      - elasticsearch
      - kafka_wait
      - kafka
